ALTER TYPE "payment_status" ADD VALUE IF NOT EXISTS 'SOURCE_PAYMENT_PENDING';
ALTER TYPE "payment_status" ADD VALUE IF NOT EXISTS 'SOURCE_PAYMENT_CONFIRMED';
ALTER TYPE "payment_status" ADD VALUE IF NOT EXISTS 'DESTINATION_PAYMENT_SUBMITTED';
ALTER TYPE "payment_status" ADD VALUE IF NOT EXISTS 'DESTINATION_PAYMENT_CONFIRMED';
ALTER TYPE "payment_status" ADD VALUE IF NOT EXISTS 'SETTLED';
